use mirajazz::{error::MirajazzError, types::DeviceInput};

use crate::mappings::{ENCODER_COUNT, KEY_COUNT, TOUCH_ZONES};

// TODO: These input mappings are placeholders and need to be verified with the actual AKP05 device
// The actual input codes will need to be discovered by testing with the real hardware
//
// Note: The touchscreen zones belong to encoders, not buttons. Similar to Stream Deck+,
// each encoder has an associated touch zone on the touchscreen strip.
// OpenDeck handles the touchscreen rendering and swipe-to-switch-page functionality automatically.

pub fn process_input(input: u8, state: u8) -> Result<DeviceInput, MirajazzError> {
    // Always emit a raw input line at debug for tracing
    log::debug!("Processing input: 0x{:02X}, state: {}", input, state);

    match input {
        // Physical LCD buttons (1-10)
        // TODO: Update button range for 10 buttons (AKP05 has 10 vs AKP03's 9)
        (0..=10) => read_button_press(input, state),

        // Touchscreen tap events (4 zones, one per encoder)
        // TODO: Discover actual input codes for touchscreen zones and verify handling mechanism
        // These are placeholders that need to be verified with real hardware
        0x40..=0x43 => read_touch_tap(input, state),

        // Touchscreen swipe events (e.g., switch pages)
        // These are generated by the touch strip; OpenDeck handles page switching.
        // We log them for diagnostics and return a non-fatal error same as taps.
        0x38 | 0x39 => read_touch_swipe(input, state),

        // Encoder rotation (4 encoders)
        0xA0 | 0xA1 | 0x50 | 0x51 | 0x90 | 0x91 | 0x70 | 0x71 => read_encoder_value(input),

        // Encoder press (4 encoders)
        0x33..=0x37 => read_encoder_press(input, state),

        _ => {
            // Unknown raw input; surface prominently to help mapping
            log::info!("EVENT Unknown code=0x{:02X} state={}", input, state);
            log::warn!("Unknown input code: 0x{:02X}, state: {}", input, state);
            Err(MirajazzError::BadData)
        }
    }
}

fn read_button_states(states: &[u8]) -> Vec<bool> {
    let mut bools = vec![];

    for i in 0..KEY_COUNT {
        bools.push(states[i + 1] != 0);
    }

    bools
}

fn read_button_press(input: u8, state: u8) -> Result<DeviceInput, MirajazzError> {
    let mut button_states = vec![0x01];
    button_states.extend(vec![0u8; KEY_COUNT + 1]);

    if input == 0 {
        return Ok(DeviceInput::ButtonStateChange(read_button_states(
            &button_states,
        )));
    }

    // TODO: Map actual AKP05 input codes to button indices (1-10)
    // This is a placeholder mapping that needs to be verified with real hardware
    let pressed_index: usize = match input {
        (1..=10) => input as usize, // 10 buttons for AKP05
        _ => return Err(MirajazzError::BadData),
    };

    button_states[pressed_index] = state;

    // Log a concise, info-level event for recognized button presses
    log::info!("EVENT Button index={} state={}", pressed_index, state);

    Ok(DeviceInput::ButtonStateChange(read_button_states(
        &button_states,
    )))
}

fn read_encoder_value(input: u8) -> Result<DeviceInput, MirajazzError> {
    let mut encoder_values = vec![0i8; ENCODER_COUNT];

    let (encoder, value): (usize, i8) = match input {
        // Encoder 1
        0xA0 => (0, -1),
        0xA1 => (0, 1),
        // Encoder 2
        0x50 => (1, -1),
        0x51 => (1, 1),
        // Encoder 3
        0x90 => (2, -1),
        0x91 => (2, 1),
        // Encoder 4
        0x70 => (3, -1),
        0x71 => (3, 1),
        _ => return Err(MirajazzError::BadData),
    };

    encoder_values[encoder] = value;

    // Log recognized encoder twist
    log::info!("EVENT EncoderTwist encoder={} delta={}", encoder, value);
    Ok(DeviceInput::EncoderTwist(encoder_values))
}

fn read_encoder_press(input: u8, state: u8) -> Result<DeviceInput, MirajazzError> {
    let mut encoder_states = vec![false; ENCODER_COUNT];

    let encoder: usize = match input {
        0x37 => 0, // Encoder 1
        0x35 => 1, // Encoder 2
        0x33 => 2, // Encoder 3
        0x36 => 3, // Encoder 4
        _ => return Err(MirajazzError::BadData),
    };

    encoder_states[encoder] = state != 0;

    // Log recognized encoder press/release
    log::info!(
        "EVENT EncoderPress encoder={} state={}",
        encoder,
        encoder_states[encoder]
    );
    Ok(DeviceInput::EncoderStateChange(encoder_states))
}

/// Touchscreen swipe handler

fn read_touch_swipe(input: u8, state: u8) -> Result<DeviceInput, MirajazzError> {
    log::info!("EVENT TouchSwipe code=0x{:02X} state={}", input, state);
    Ok(DeviceInput::NoData)
}

fn read_touch_tap(input: u8, state: u8) -> Result<DeviceInput, MirajazzError> {
    let mut touch_states = vec![false; TOUCH_ZONES];

    let zone = match input {
        0x40 => 0, // Left-most encoder zone
        0x41 => 1,
        0x42 => 2,
        0x43 => 3, // Right-most encoder zone
        _ => return Err(MirajazzError::BadData),
    };

    let active = state != 0;
    touch_states[zone] = active;

    log::info!("EVENT TouchTap zone={} active={}", zone, active);

    Ok(DeviceInput::EncoderStateChange(touch_states))
}
